# Generated by cucumber-sinatra. (2015-02-18 18:03:16 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'hello_again.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = hello_world_again

class hello_world_againWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  hello_world_againWorld.new
end
